// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efwprcstgmtwqoecqfpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmd3ByY3N0Z210d3FvZWNxZnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzk4MTQsImV4cCI6MjA1NTc1NTgxNH0.lvcA-LOk3bEr7vB_2lJk2sDFjwDw9Xh4B4D9tqbGjJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);